In [1]:
import pandas as pd
from datetime import datetime
import numpy as np
from random import choice
from string import ascii_letters, digits
import time

In [2]:
metadata = dict(num=[1, 16], 
                char=[5], 
                varchar=[5], 
                date=['2021.1.1', '2022.1.1'], 
                timestamp=['2021.1.1 6:10:8', '2022.1.1 6:10:8'],
                col_set=(1,2,3,4,5,678),
                num_mask='123####45345', 
                str_mask = ('sdft####sasdf'))
RECORDS_COUNT = 1000

In [3]:
metadata

{'num': [1, 16],
 'char': [5],
 'varchar': [5],
 'date': ['2021.1.1', '2022.1.1'],
 'timestamp': ['2021.1.1 6:10:8', '2022.1.1 6:10:8'],
 'col_set': (1, 2, 3, 4, 5, 678),
 'num_mask': '123####45345',
 'str_mask': 'sdft####sasdf'}

In [4]:
datetime.strptime(metadata['date'][0], '%Y.%m.%d').date()

datetime.date(2021, 1, 1)

In [5]:
datetime.strptime(metadata['timestamp'][0], '%Y.%m.%d %H:%M:%S')

datetime.datetime(2021, 1, 1, 6, 10, 8)

In [6]:
df = pd.DataFrame()
cnt = 0

for i in metadata.keys():
    if i == 'num':
        df[str(cnt)] = np.random.randint(metadata[i][0], metadata[i][1]+1, RECORDS_COUNT)
        
    elif i == 'char':
        df[str(cnt)] = np.array([''.join([choice(ascii_letters) 
                                          for i in range(metadata[i][0])]) 
                                 for j in range(RECORDS_COUNT)])
        
    elif i == 'varchar':
        df[str(cnt)] = np.array([''.join([choice(ascii_letters) 
                                          for i in range(1+np.random.choice(metadata[i][0]))]) 
                                 for j in range(RECORDS_COUNT)])
        
    elif i == 'date':
        start = time.mktime(time.strptime(metadata['date'][0], '%Y.%m.%d'))
        finish = time.mktime(time.strptime(metadata['date'][1], '%Y.%m.%d'))
        rand_arr = np.random.random_sample((RECORDS_COUNT,)) * (finish - start)
        df[str(cnt)] = [time.strftime('%Y.%m.%d', time.localtime(i + start)) for i in rand_arr]
        
    elif i == 'timestamp':
        start = time.mktime(time.strptime(metadata['timestamp'][0], '%Y.%m.%d %H:%M:%S'))
        finish = time.mktime(time.strptime(metadata['timestamp'][1], '%Y.%m.%d %H:%M:%S'))
        rand_arr = np.random.random_sample((RECORDS_COUNT,)) * (finish - start)
        df[str(cnt)] = [time.strftime('%Y.%m.%d %H:%M:%S', time.localtime(i + start)) for i in rand_arr]
        
    elif i == 'col_set':
        df[str(cnt)] = np.random.choice(metadata['col_set'], RECORDS_COUNT)

    elif i == 'num_mask':
        lst = [metadata['num_mask']] * RECORDS_COUNT
        lst = [''.join([i if i != '#' else np.random.choice(list(''.join(choice(digits)))) for i in metadata['num_mask']]) for i1 in lst]
        df[str(cnt)] = lst
        
    elif i == 'str_mask':
        lst = [metadata['str_mask']] * RECORDS_COUNT
        lst = [''.join([i if i != '#' else np.random.choice(list(''.join(choice(ascii_letters)))) for i in metadata['str_mask']]) for i1 in lst]
        df[str(cnt)] = lst
        
    cnt += 1

In [8]:
df.head(30)

,0,1,2,3,4,5,6,7
0,5,linrt,dTLs,2021.02.14,2021.04.19 08:00:32,3,123298345345,sdftomDlsasdf
1,15,IXnXl,FGcb,2021.11.03,2021.09.06 06:06:27,678,123053845345,sdftlHvKsasdf
2,8,djlna,jF,2021.03.18,2021.07.25 23:01:33,3,123219845345,sdftDoDOsasdf
3,2,bnFDn,usjTv,2021.09.03,2021.01.25 03:00:09,3,123583245345,sdftJThasasdf
4,2,ZTVSg,HNZwF,2021.04.05,2021.10.29 11:59:55,1,123309845345,sdftVqhGsasdf
5,9,UBPAw,TuO,2021.01.15,2021.01.12 16:18:47,4,123554745345,sdftKOctsasdf
6,14,HQMKp,dT,2021.09.17,2021.08.09 22:15:09,3,123870845345,sdftxvnLsasdf
7,2,OnnGj,wCL,2021.07.26,2021.02.16 07:50:32,3,123022945345,sdftmHwosasdf
8,13,tlyWH,wuasS,2021.10.28,2021.10.26 00:12:46,2,123559445345,sdftnbYcsasdf
9,6,aeEYx,TqJ,2021.01.13,2021.08.21 14:39:27,4,123446445345,sdftdWfHsasdf
10,13,dixoh,wD,2021.09.30,2021.09.23 21:53:35,4,123037945345,sdftMqdwsasdf
11,12,hsUtI,i,2021.02.21,2021.12.18 03:12:47,3,123150845345,sdftpItGsasdf
12,14,vMgmu,lx,2021.05.20,2021.03.23 07:03:50,1,123592945345,sdftKeNCsasdf
13,2,hoBVi,cMHNu,2021.03.20,2021.10.15 06:44:13,1,123690345345,sdftBLXisasdf
14,12,mWflw,Zl,2021.05.09,2021.10.19 04:11:19,678,123085245345,sdftFRKzsasdf
15,1,BqjYj,CkKr,2021.05.19,2021.12.26 15:55:16,678,123959445345,sdftZNZTsasdf
16,8,VDlvm,gNfy,2021.08.10,2021.10.29 19:23:09,1,123330045345,sdftrKhEsasdf
17,16,OrkrG,vPdvc,2021.11.21,2021.10.31 17:12:28,5,123335145345,sdftoVfrsasdf
18,3,hUaRA,YvQKB,2021.09.03,2021.06.01 02:31:40,2,123839145345,sdftlQmHsasdf
19,7,hLwKW,Tzn,2021.12.03,2021.11.15 04:45:57,4,123026445345,sdftJwVRsasdf
20,4,dosUj,F,2021.07.26,2021.11.11 14:48:12,4,123800945345,sdftQMPVsasdf
21,12,vHwsO,n,2021.08.31,2021.12.18 17:06:42,2,123732445345,sdftvJOGsasdf
22,1,QuArn,FbHY,2021.01.27,2021.08.26 18:48:40,1,123185945345,sdftvmJVsasdf
23,3,NBMyj,nmBw,2021.10.02,2021.06.07 21:24:57,5,123131245345,sdfthttwsasdf
24,10,MoiSx,rNxDc,2021.10.23,2021.05.26 22:57:59,3,123754445345,sdftFZBysasdf
25,15,ZrpvF,x,2021.12.01,2021.11.03 23:49:52,3,123509045345,sdftUzcOsasdf
26,6,StvKQ,F,2021.03.19,2021.05.01 23:44:37,4,123815745345,sdftqWsbsasdf
27,3,KHIJi,BCS,2021.08.08,2021.01.31 10:20:43,678,123821745345,sdftSqIfsasdf
28,4,IlFMf,MAF,2021.07.18,2021.06.12 21:52:49,2,123772945345,sdftdQtysasdf
29,15,JxcYL,lgLfL,2021.09.01,2021.12.31 09:12:34,5,123079445345,sdftTbmGsasdf